### ISSUE TITLE
Feature request: display multiple stack dependencies

### ISSUE THREAD

**Issue by tmizuma** [pistazie/cdk-dia#19] opened 2021-12-17 08:24 UTC
I tried `cdk-dia` today and it looks great. 

Currently, multiple stacks dependencies can't be displayed because `cdk-dia` creates diagrams for each stack.
I personally think it can be very useful if it displays a diagram that can define the dependencies between each stack.

or, is there any way to display multiple stack dependencies? Thanks!
![diagram](https://user-images.githubusercontent.com/19788436/146512909-87ce04bb-399b-43f4-8c81-d07294526685.png)

**Comment by pistazie** [comment] 2021-12-19 12:14
thanks @tmizuma. 

Duplicate of #17 - isn't it?

what CDK-Dia version did you use? 0.6.1 should show such relationships/edges. 

If you used 0.6.1 it would be great if you could supply the tree.json created in your cdk.out folder after runnign cdk commands (`cdk diff`, `cdk synth` or `cdk deploy`)

**Comment by tmizuma** [comment] 2021-12-20 00:56
Thanks for the reply.
I could create a diagram I expect after upgrading cdk-dia.
![diagram](https://user-images.githubusercontent.com/19788436/146697608-634ccc95-998d-4d24-89ab-0a81e24e889d.png)

**Closed** 2021-12-20 09:45 UTC
